/**
 * Master list of all Colombian Fintech regulatory norms to download.
 * Each entry has: id, name, year, authority, url, type, temas (relevant verticals)
 */

export interface NormSource {
  id: string;
  name: string;
  year: number;
  authority: string;
  url: string;
  type: "ley" | "decreto" | "circular" | "resolucion" | "documento";
  temas: string[];
  priority: 1 | 2 | 3; // 1 = critical, 2 = important, 3 = nice-to-have
}

export const NORM_SOURCES: NormSource[] = [
  // ═══ PRIORITY 1: Core Fintech Framework ═══

  // Laws
  {
    id: "ley-1735-2014",
    name: "Ley 1735 de 2014 — SEDPE",
    year: 2014,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=59835",
    type: "ley",
    temas: ["Neobancos", "Pagos Digitales"],
    priority: 1,
  },
  {
    id: "ley-1328-2009",
    name: "Ley 1328 de 2009 — Protección Consumidor Financiero",
    year: 2009,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=34488",
    type: "ley",
    temas: ["Crédito Digital", "Crowdfunding", "Insurtech", "Neobancos", "Pagos Digitales", "WealthTech"],
    priority: 1,
  },
  {
    id: "ley-1581-2012",
    name: "Ley 1581 de 2012 — Protección Datos Personales",
    year: 2012,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=49981",
    type: "ley",
    temas: ["Protección Datos"],
    priority: 1,
  },
  {
    id: "ley-964-2005",
    name: "Ley 964 de 2005 — Mercado de Valores",
    year: 2005,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=22412",
    type: "ley",
    temas: ["Crowdfunding", "WealthTech"],
    priority: 1,
  },
  {
    id: "ley-527-1999",
    name: "Ley 527 de 1999 — Comercio Electrónico y Firma Digital",
    year: 1999,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=4276",
    type: "ley",
    temas: ["Firma Electrónica"],
    priority: 1,
  },
  {
    id: "ley-1266-2008",
    name: "Ley 1266 de 2008 — Habeas Data Financiero",
    year: 2008,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=34488",
    type: "ley",
    temas: ["Crédito Digital", "Protección Datos"],
    priority: 1,
  },
  {
    id: "ley-1480-2011",
    name: "Ley 1480 de 2011 — Estatuto del Consumidor",
    year: 2011,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=44306",
    type: "ley",
    temas: ["Crédito Digital", "Pagos Digitales"],
    priority: 1,
  },

  // Key Decrees
  {
    id: "decreto-1357-2018",
    name: "Decreto 1357 de 2018 — Crowdfunding",
    year: 2018,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=87770",
    type: "decreto",
    temas: ["Crowdfunding"],
    priority: 1,
  },
  {
    id: "decreto-1234-2020",
    name: "Decreto 1234 de 2020 — Sandbox Regulatorio",
    year: 2020,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=142005",
    type: "decreto",
    temas: ["Sandbox"],
    priority: 1,
  },
  {
    id: "decreto-661-2018",
    name: "Decreto 661 de 2018 — Robo-Advisory",
    year: 2018,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=86121",
    type: "decreto",
    temas: ["WealthTech"],
    priority: 1,
  },
  {
    id: "decreto-1491-2015",
    name: "Decreto 1491 de 2015 — Reglamentación SEDPE",
    year: 2015,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=63650",
    type: "decreto",
    temas: ["Neobancos", "Pagos Digitales"],
    priority: 1,
  },
  {
    id: "decreto-1692-2020",
    name: "Decreto 1692 de 2020 — Sistemas de Pago Bajo Valor",
    year: 2020,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=150762",
    type: "decreto",
    temas: ["Pagos Digitales"],
    priority: 1,
  },
  {
    id: "decreto-1297-2022",
    name: "Decreto 1297 de 2022 — Open Banking Marco",
    year: 2022,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=189805",
    type: "decreto",
    temas: ["Open Banking"],
    priority: 1,
  },

  // ═══ PRIORITY 2: Important complementary norms ═══

  {
    id: "ley-1955-2019",
    name: "Ley 1955 de 2019 — PND (Art. 166 Sandbox)",
    year: 2019,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=93970",
    type: "ley",
    temas: ["Sandbox"],
    priority: 2,
  },
  {
    id: "ley-2069-2020",
    name: "Ley 2069 de 2020 — Emprendimiento",
    year: 2020,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=160966",
    type: "ley",
    temas: ["Sandbox"],
    priority: 2,
  },
  {
    id: "ley-1231-2008",
    name: "Ley 1231 de 2008 — Factura como Título Valor",
    year: 2008,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=31431",
    type: "ley",
    temas: ["Factoring"],
    priority: 2,
  },
  {
    id: "ley-2157-2021",
    name: "Ley 2157 de 2021 — Borrón y Cuenta Nueva (Habeas Data)",
    year: 2021,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=172549",
    type: "ley",
    temas: ["Crédito Digital", "Protección Datos"],
    priority: 2,
  },
  {
    id: "ley-2439-2024",
    name: "Ley 2439 de 2024 — Consumidor E-commerce",
    year: 2024,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=226878",
    type: "ley",
    temas: ["Pagos Digitales", "Crédito Digital"],
    priority: 2,
  },
  {
    id: "decreto-1235-2020",
    name: "Decreto 1235 de 2020 — Crowdfunding Ampliado",
    year: 2020,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=142006",
    type: "decreto",
    temas: ["Crowdfunding"],
    priority: 2,
  },
  {
    id: "decreto-222-2020",
    name: "Decreto 222 de 2020 — Depósitos Simplificados",
    year: 2020,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=105824",
    type: "decreto",
    temas: ["Pagos Digitales", "Neobancos"],
    priority: 2,
  },
  {
    id: "decreto-2443-2018",
    name: "Decreto 2443 de 2018 — Inversión en Fintechs",
    year: 2018,
    authority: "MinHacienda",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=90855",
    type: "decreto",
    temas: ["Crédito Digital", "Neobancos"],
    priority: 2,
  },
  {
    id: "decreto-1154-2020",
    name: "Decreto 1154 de 2020 — Factura Electrónica como Título Valor",
    year: 2020,
    authority: "MinComercio",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=139287",
    type: "decreto",
    temas: ["Factoring"],
    priority: 2,
  },
  {
    id: "decreto-2364-2012",
    name: "Decreto 2364 de 2012 — Firma Electrónica",
    year: 2012,
    authority: "MinComercio",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=50583",
    type: "decreto",
    temas: ["Firma Electrónica"],
    priority: 2,
  },
  {
    id: "decreto-1377-2013",
    name: "Decreto 1377 de 2013 — Reglamentación Datos Personales",
    year: 2013,
    authority: "MinComercio",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=53646",
    type: "decreto",
    temas: ["Protección Datos"],
    priority: 2,
  },

  // ═══ PRIORITY 3: Complementary ═══

  {
    id: "ley-1527-2012",
    name: "Ley 1527 de 2012 — Libranzas",
    year: 2012,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=47213",
    type: "ley",
    temas: ["Crédito Digital"],
    priority: 3,
  },
  {
    id: "ley-2195-2022",
    name: "Ley 2195 de 2022 — Transparencia/SAGRILAFT",
    year: 2022,
    authority: "Congreso",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=176283",
    type: "ley",
    temas: ["SARLAFT"],
    priority: 3,
  },
  {
    id: "decreto-1732-2021",
    name: "Decreto 1732 de 2021 — Sandbox Multisectorial",
    year: 2021,
    authority: "MinComercio",
    url: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=175698",
    type: "decreto",
    temas: ["Sandbox"],
    priority: 3,
  },
];
